In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [73]:
# import data
import pandas as pd
df=pd.read_csv('/content/gdrive/MyDrive/pytorch learning and project/liner regression from scratch/airfoil_self_noise.csv',header=None)

In [74]:
df.columns=['Freq','Angle','Chord_length','Free_stream','d_thickness','targets']
df.shape

(1503, 6)

In [75]:
df.head()

Freq  Angle  Chord_length  Free_stream  d_thickness  targets
0   800    0.0        0.3048         71.3     0.002663  126.201
1  1000    0.0        0.3048         71.3     0.002663  125.201
2  1250    0.0        0.3048         71.3     0.002663  125.951
3  1600    0.0        0.3048         71.3     0.002663  127.591
4  2000    0.0        0.3048         71.3     0.002663  127.461

In [76]:
#check null values
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.shape

(1503, 6)

In [77]:
import torch 
import numpy as np

In [78]:
# Input array
inputs = np.array(df.drop('targets', 1), dtype='float32')
targets = np.array(df['targets'], dtype='float32')

In [79]:
inputs.shape,targets.shape

((1503, 5), (1503,))

In [80]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[8.0000e+02, 0.0000e+00, 3.0480e-01, 7.1300e+01, 2.6634e-03],
        [1.0000e+03, 0.0000e+00, 3.0480e-01, 7.1300e+01, 2.6634e-03],
        [1.2500e+03, 0.0000e+00, 3.0480e-01, 7.1300e+01, 2.6634e-03],
        ...,
        [4.0000e+03, 1.5600e+01, 1.0160e-01, 3.9600e+01, 5.2849e-02],
        [5.0000e+03, 1.5600e+01, 1.0160e-01, 3.9600e+01, 5.2849e-02],
        [6.3000e+03, 1.5600e+01, 1.0160e-01, 3.9600e+01, 5.2849e-02]])
tensor([126.2010, 125.2010, 125.9510,  ..., 106.6040, 106.2240, 104.2040])


In [81]:
import torch.nn as nn
from torch.utils.data import TensorDataset

In [82]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[8.0000e+02, 0.0000e+00, 3.0480e-01, 7.1300e+01, 2.6634e-03],
         [1.0000e+03, 0.0000e+00, 3.0480e-01, 7.1300e+01, 2.6634e-03],
         [1.2500e+03, 0.0000e+00, 3.0480e-01, 7.1300e+01, 2.6634e-03]]),
 tensor([126.2010, 125.2010, 125.9510]))

## Data loader module

In [83]:
from torch.utils.data import DataLoader
# Define data loader
batch_size = 40
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

lets see the train_dl created by data loader

In [84]:
for xb, yb in train_dl:
    print(xb)# trainning the batches 
    print(yb)# targets of batches
    break

tensor([[1.6000e+03, 9.9000e+00, 1.5240e-01, 5.5500e+01, 2.0844e-02],
        [1.0000e+04, 3.3000e+00, 1.0160e-01, 3.9600e+01, 2.4514e-03],
        [3.1500e+03, 0.0000e+00, 1.0160e-01, 5.5500e+01, 1.3198e-03],
        [8.0000e+02, 4.0000e+00, 2.2860e-01, 3.1700e+01, 5.0907e-03],
        [1.2500e+03, 4.0000e+00, 3.0480e-01, 3.9600e+01, 5.7964e-03],
        [1.0000e+03, 0.0000e+00, 3.0480e-01, 3.1700e+01, 3.3127e-03],
        [2.0000e+04, 0.0000e+00, 2.5400e-02, 5.5500e+01, 4.1229e-04],
        [2.5000e+02, 1.1200e+01, 5.0800e-02, 3.9600e+01, 1.5048e-02],
        [1.0000e+03, 2.0000e+00, 2.2860e-01, 3.1700e+01, 3.7237e-03],
        [4.0000e+03, 2.0000e+00, 2.2860e-01, 7.1300e+01, 2.9303e-03],
        [2.0000e+03, 2.2200e+01, 2.5400e-02, 7.1300e+01, 2.1418e-02],
        [8.0000e+03, 1.5000e+00, 3.0480e-01, 3.9600e+01, 3.9211e-03],
        [5.0000e+02, 7.3000e+00, 2.2860e-01, 5.5500e+01, 1.1171e-02],
        [2.5000e+03, 0.0000e+00, 1.5240e-01, 7.1300e+01, 1.5988e-03],
        [1.6000e+03,

## nn.Linear

In [85]:
# Define model, and initialize the weights 
model = nn.Linear(5, 1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3905, -0.0265, -0.1608,  0.4329, -0.0142]], requires_grad=True)
Parameter containing:
tensor([-0.2555], requires_grad=True)


In [86]:
# Parameters: check all the model parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3905, -0.0265, -0.1608,  0.4329, -0.0142]], requires_grad=True),
 Parameter containing:
 tensor([-0.2555], requires_grad=True)]

In [87]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 342.9602],
        [ 421.0599],
        [ 518.6844],
        ...,
        [1578.4497],
        [1968.9479],
        [2476.5955]], grad_fn=<AddmmBackward>)

## loss function

In [88]:
# Import nn.functional
import torch.nn.functional as F

In [89]:
# Define loss function
loss_fn = F.mse_loss
pred=model(inputs)
loss = torch.sqrt(loss_fn(pred.squeeze(), targets))
print(loss)

tensor(1603.6962, grad_fn=<SqrtBackward>)


# Optimizer 

In [90]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-6)

# Model Training

In [91]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            # 2. Calculate loss
            loss = torch.sqrt(loss_fn(pred.squeeze(), yb))
            #print(loss)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [96]:
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], Loss: 56.6340
Epoch [20/1000], Loss: 62.1094
Epoch [30/1000], Loss: 54.4285
Epoch [40/1000], Loss: 58.8738
Epoch [50/1000], Loss: 58.0038
Epoch [60/1000], Loss: 53.0567
Epoch [70/1000], Loss: 50.6935
Epoch [80/1000], Loss: 50.1212
Epoch [90/1000], Loss: 53.0992
Epoch [100/1000], Loss: 59.9753
Epoch [110/1000], Loss: 52.4111
Epoch [120/1000], Loss: 48.3595
Epoch [130/1000], Loss: 51.8777
Epoch [140/1000], Loss: 63.5481
Epoch [150/1000], Loss: 58.9241
Epoch [160/1000], Loss: 48.8526
Epoch [170/1000], Loss: 52.1454
Epoch [180/1000], Loss: 53.7029
Epoch [190/1000], Loss: 49.2592
Epoch [200/1000], Loss: 45.5795
Epoch [210/1000], Loss: 59.0615
Epoch [220/1000], Loss: 49.9361
Epoch [230/1000], Loss: 48.3509
Epoch [240/1000], Loss: 40.4836
Epoch [250/1000], Loss: 47.1151
Epoch [260/1000], Loss: 51.3183
Epoch [270/1000], Loss: 48.9462
Epoch [280/1000], Loss: 45.8728
Epoch [290/1000], Loss: 46.6376
Epoch [300/1000], Loss: 44.9528
Epoch [310/1000], Loss: 47.4584
Epoch [320/1000],

In [97]:
# Generate predictions
preds = model(inputs)
preds

tensor([[137.4814],
        [138.4127],
        [139.5769],
        ...,
        [ 96.6557],
        [101.3124],
        [107.3660]], grad_fn=<AddmmBackward>)

Model prediction is resonable as the pred and targets values are clsoed 

In [98]:
# Compare with targets
targets,preds

(tensor([126.2010, 125.2010, 125.9510,  ..., 106.6040, 106.2240, 104.2040]),
 tensor([[137.4814],
         [138.4127],
         [139.5769],
         ...,
         [ 96.6557],
         [101.3124],
         [107.3660]], grad_fn=<AddmmBackward>))